/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Lists.*;
import dinhnghia.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import jdbc.*;
import File.*;
import check.*;
import java.io.File;

/**
 *
 * @author Admin
 */
public class AdminUI extends javax.swing.JFrame {

    NhanVien nhanVien;
    HangHoaJDBC hangHoaJDBC;
    NhanVienJDBC nhanVienJDBC;
    HoaDonJDBC donJDBC;
    ChiTietHoaDonJDBC chiTietHoaDonJDBC;
    
    DanhSachHangHoa danhSachHangHoa;
    DanhSachHoaDon danhSachHoaDon;
    DanhSachChiTietHoaDon danhSachChiTietHoaDon;
    DanhSachNhanVien danhSachNhanVien;

    DefaultTableModel bangNhanVien;
    DefaultTableModel bangHangHoa;

    ArrayList<NhanVien> listNhanVien = null;
    ArrayList<HangHoa> listHangHoa = null;
    ArrayList<ChiTietHoaDon> listChiTietHoaDon = null;
    ArrayList<HoaDon> listHoaDon = null;
    Pattern checkValidPhone = Pattern.compile("^0\\d{9}$");
    CheckDate checkDate = new CheckDate();
    
    FileIO fileIO=new FileIO();
    int clickNV = -1;
    int clickHH=-1;
    String fileName="thongBao.txt";
    boolean isOpen=false;
    String maNV;
    /**
     * Creates new form AdminUI
     */
    //  final JTextField textFieldA = new HintTextField("A hint here");
    public AdminUI(String dataController) throws Exception {
        initComponents();
        hangHoaJDBC = new HangHoaJDBC();
        nhanVienJDBC = new NhanVienJDBC();
        donJDBC = new HoaDonJDBC();
        nhanVien = new NhanVien();
        chiTietHoaDonJDBC = new ChiTietHoaDonJDBC();
        danhSachHangHoa = new DanhSachHangHoa();
        danhSachHoaDon = new DanhSachHoaDon();
        danhSachNhanVien = new DanhSachNhanVien();
        danhSachChiTietHoaDon = new DanhSachChiTietHoaDon();

        listNhanVien = nhanVienJDBC.getDataNhanVien();
        listHangHoa = hangHoaJDBC.getDataHangHoa();
        listHoaDon = donJDBC.getDataHoaDon();
        listChiTietHoaDon = chiTietHoaDonJDBC.getDataChiTietHoaDon();
        danhSachHangHoa.setList(listHangHoa);
        danhSachHangHoa.setList(listHangHoa);
        danhSachNhanVien.setList(listNhanVien);
        danhSachChiTietHoaDon.setList(listChiTietHoaDon);
        bangNhanVien = (DefaultTableModel) nhanVienTable.getModel();
        bangHangHoa = (DefaultTableModel) hangHoaTable.getModel();
        showComboBox();
        displayDanhSachHangHoa();
        displayDanhSachNhanVien();
        maNV=dataController;
        this.setLocationRelativeTo(null);
    }
   

    private AdminUI() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        taoThongBaoPanel = new javax.swing.JTabbedPane();
        doanhThuPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nhanVienPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        maNVTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tenNVTextField = new javax.swing.JTextField();
        chucVuComboBox = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        nhanVienTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        soDienThoaiTextField = new javax.swing.JTextField();
        ngaySinhTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        themNhanVienButton = new javax.swing.JButton();
        suaNhanVienButton = new javax.swing.JButton();
        xoaNhanVienButton = new javax.swing.JButton();
        xoaTatCaNhanVienButton = new javax.swing.JButton();
        resetNhanVienButton = new javax.swing.JButton();
        timKiemNhanVienTextField = new javax.swing.JTextField();
        timKiemNhanVienButton = new javax.swing.JButton();
        hangHoaPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        hangHoaTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        maHHTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tenHHTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nhaCungCapTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        soLuongSpinner = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        giaNhapTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        giaBanTextField = new javax.swing.JTextField();
        suaHangHoaButton = new javax.swing.JButton();
        timKiemHangHoaButton = new javax.swing.JButton();
        timKiemHangHoaTextField = new javax.swing.JTextField();
        resetHangHoaButton = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(backButton)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(backButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REVENUE");

        javax.swing.GroupLayout doanhThuPanelLayout = new javax.swing.GroupLayout(doanhThuPanel);
        doanhThuPanel.setLayout(doanhThuPanelLayout);
        doanhThuPanelLayout.setHorizontalGroup(
            doanhThuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doanhThuPanelLayout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(369, Short.MAX_VALUE))
        );
        doanhThuPanelLayout.setVerticalGroup(
            doanhThuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doanhThuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(530, Short.MAX_VALUE))
        );

        taoThongBaoPanel.addTab("Doanh Thu", doanhThuPanel);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MaNV");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TenNV");

        nhanVienTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "MaNV", "Ten NV", "Chuc Vu", "SDT", "Ngay Sinh"
            }
        ));
        nhanVienTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nhanVienTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(nhanVienTable);

        jLabel7.setText("Danh Sach Nhan Vien");

        jLabel8.setText("So Dien Thoai");

        ngaySinhTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngaySinhTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("Ngay Sinh");

        themNhanVienButton.setText("Them");
        themNhanVienButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themNhanVienButtonActionPerformed(evt);
            }
        });

        suaNhanVienButton.setText("Sua");
        suaNhanVienButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaNhanVienButtonActionPerformed(evt);
            }
        });

        xoaNhanVienButton.setText("Xoa");
        xoaNhanVienButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaNhanVienButtonActionPerformed(evt);
            }
        });

        xoaTatCaNhanVienButton.setText("Xoa tat ca");
        xoaTatCaNhanVienButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaTatCaNhanVienButtonActionPerformed(evt);
            }
        });

        resetNhanVienButton.setText("Reset");
        resetNhanVienButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetNhanVienButtonActionPerformed(evt);
            }
        });

        timKiemNhanVienButton.setText("Tim Kiem");
        timKiemNhanVienButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timKiemNhanVienButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nhanVienPanelLayout = new javax.swing.GroupLayout(nhanVienPanel);
        nhanVienPanel.setLayout(nhanVienPanelLayout);
        nhanVienPanelLayout.setHorizontalGroup(
            nhanVienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhanVienPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(nhanVienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(nhanVienPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tenNVTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(nhanVienPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maNVTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addGroup(nhanVienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(nhanVienPanelLayout.createSequentialGroup()
                                .addComponent(chucVuComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addGroup(nhanVienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(nhanVienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ngaySinhTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(soDienThoaiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(nhanVienPanelLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(nhanVienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(themNhanVienButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resetNhanVienButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(127, 127, 127)
                        .addGroup(nhanVienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(suaNhanVienButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xoaTatCaNhanVienButton))
                        .addGap(137, 137, 137)
                        .addGroup(nhanVienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xoaNhanVienButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(nhanVienPanelLayout.createSequentialGroup()
                                .addComponent(timKiemNhanVienTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(timKiemNhanVienButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        nhanVienPanelLayout.setVerticalGroup(
            nhanVienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nhanVienPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(nhanVienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chucVuComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maNVTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soDienThoaiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nhanVienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(nhanVienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tenNVTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ngaySinhTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(nhanVienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themNhanVienButton)
                    .addComponent(suaNhanVienButton)
                    .addComponent(xoaNhanVienButton))
                .addGap(18, 18, 18)
                .addGroup(nhanVienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xoaTatCaNhanVienButton)
                    .addComponent(resetNhanVienButton)
                    .addComponent(timKiemNhanVienTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timKiemNhanVienButton))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        taoThongBaoPanel.addTab("Nhan Vien", nhanVienPanel);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hang Hoa");

        hangHoaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "MaHH", "TenHH", "Nha Cung Cap", "So Luong", "Gia Nhap", "Gia Ban"
            }
        ));
        hangHoaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hangHoaTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(hangHoaTable);

        jLabel4.setText("MaHH");

        jLabel6.setText("Ten HH");

        jLabel10.setText("Nha Cung Cap");

        jLabel11.setText("So Luong");

        jLabel12.setText("Gia NHap");

        jLabel14.setText("Gia Ban");

        suaHangHoaButton.setText("Sua");
        suaHangHoaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaHangHoaButtonActionPerformed(evt);
            }
        });

        timKiemHangHoaButton.setText("Tim Kiem");
        timKiemHangHoaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timKiemHangHoaButtonActionPerformed(evt);
            }
        });

        resetHangHoaButton.setText("Reset");
        resetHangHoaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetHangHoaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout hangHoaPanelLayout = new javax.swing.GroupLayout(hangHoaPanel);
        hangHoaPanel.setLayout(hangHoaPanelLayout);
        hangHoaPanelLayout.setHorizontalGroup(
            hangHoaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hangHoaPanelLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(hangHoaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hangHoaPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maHHTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nhaCungCapTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(soLuongSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(hangHoaPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(hangHoaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tenHHTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(hangHoaPanelLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(resetHangHoaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(75, 75, 75)
                        .addGroup(hangHoaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hangHoaPanelLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(giaNhapTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(giaBanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(hangHoaPanelLayout.createSequentialGroup()
                                .addComponent(suaHangHoaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115)
                                .addComponent(timKiemHangHoaTextField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(timKiemHangHoaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(59, 59, 59))
            .addGroup(hangHoaPanelLayout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        hangHoaPanelLayout.setVerticalGroup(
            hangHoaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hangHoaPanelLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(hangHoaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maHHTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nhaCungCapTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soLuongSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hangHoaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hangHoaPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(hangHoaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tenHHTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(giaBanTextField)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(giaNhapTextField))
                .addGap(91, 91, 91)
                .addGroup(hangHoaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timKiemHangHoaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timKiemHangHoaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetHangHoaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suaHangHoaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        taoThongBaoPanel.addTab("Hang Hoa", hangHoaPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taoThongBaoPanel))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(taoThongBaoPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean isInt(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    public void displayDanhSachNhanVien() {
        for (int i = 0; i < danhSachNhanVien.getSize(); i++) {
            showTableNhanVien((i + 1), danhSachNhanVien.getNhanVienAtIndex(i));
        }
    }

    public void showTableNhanVien(int index, NhanVien n) {
        bangNhanVien.addRow(new Object[]{
            index, n.getMaNV(), n.getTenNV(), n.getChucVu(), n.getNgaySinh(), n.getSoDienThoai()
        });
    }

    public void displayDanhSachHangHoa() {
        for (int i = 0; i < danhSachHangHoa.getSize(); i++) {
            showTableHangHoa((i + 1), danhSachHangHoa.getHangHoaAtIndex(i));
        }
    }

    public void showTableHangHoa(int index, HangHoa n) {
        bangHangHoa.addRow(new Object[]{
            index, n.getMaHH(), n.getTenHangHoa(), n.getNhaCungCap(), n.getSoLuong(), n.getGiaNhap(), n.getGiaBan()
        });
    }

    public boolean emptyCheckNhanVien() {
        if (String.valueOf(maNVTextField.getText()).equals("")) {
            JOptionPane.showMessageDialog(this, "Nhap ma nV");
            maNVTextField.requestFocus();
            return true;
        }
        if (String.valueOf(tenNVTextField.getText()).equals("")) {
            JOptionPane.showMessageDialog(this, "Nhap ten nV");
            tenNVTextField.requestFocus();
            return true;
        }
        if (String.valueOf(soDienThoaiTextField.getText()).equals("")) {
            JOptionPane.showMessageDialog(this, "Nhap so dien thoai");
            soDienThoaiTextField.requestFocus();
            return true;
        }
        if (checkValidPhone.matcher(soDienThoaiTextField.getText().toString()).find() == false) {
            JOptionPane.showMessageDialog(this, "Please input a valid phone number");
            soDienThoaiTextField.requestFocus();
            return true;
        }
        if (ngaySinhTextField.getText().toString().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhap ten ngay sinh");
            ngaySinhTextField.requestFocus();
            return true;
        }
        if (checkDate.isValidDate(ngaySinhTextField.getText().toString().trim()) == false) {
            JOptionPane.showMessageDialog(this, "Please input a valid date of birth");
            ngaySinhTextField.requestFocus();
            return true;
        }
        return false;
    }

    public boolean emptyCheckHangHoa() {
        if (maHHTextField.getText().toString().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhap ma hang hoa");
            maHHTextField.requestFocus();
            return true;
        }
        if (tenHHTextField.getText().toString().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhap ten hang hoa");
            tenHHTextField.requestFocus();
            return true;
        }
        if (nhaCungCapTextField.getText().toString().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhap nha cung cap");
            nhaCungCapTextField.requestFocus();
            return true;
        }
        if (giaNhapTextField.getText().toString().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhap gia nhap");
            giaNhapTextField.requestFocus();
            return true;
        }
        if (giaBanTextField.getText().toString().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhap gia ban");
            giaBanTextField.requestFocus();
            return true;
        }
        if (Integer.parseInt(soLuongSpinner.getValue().toString()) <= 0) {
            JOptionPane.showMessageDialog(this, "Nhap gia ban");
            soLuongSpinner.requestFocus();
            return true;
        }
        if (isInt(giaNhapTextField.getText().toString()) == false) {
            JOptionPane.showMessageDialog(this, "Please input a valid number");
            giaNhapTextField.requestFocus();
            return true;
        }
        if (isInt(giaBanTextField.getText().toString()) == false) {
            JOptionPane.showMessageDialog(this, "Please input a valid number");
            giaBanTextField.requestFocus();
            return true;
        }
        return false;
    }

    public NhanVien getNhanVienFromForm() {
        NhanVien nv = new NhanVien();
        nv.setMaNV(maNVTextField.getText().trim());
        nv.setTenNV(tenNVTextField.getText().trim());
        nv.setChucVu(chucVuComboBox.getSelectedItem().toString());
        nv.setMatKhau("123456");
        nv.setSoDienThoai(soDienThoaiTextField.getText().toString().trim());
        nv.setNgaySinh(ngaySinhTextField.getText().trim());
        return nv;
    }

    public HangHoa getHangHoaFromForm(){
        HangHoa hh=new HangHoa();
        hh.setGiaBan(Integer.parseInt(giaBanTextField.getText()));
        hh.setGiaNhap(Integer.parseInt(giaNhapTextField.getText()));
        hh.setMaHH(maHHTextField.getText());
        hh.setTenHangHoa(tenHHTextField.getText());
        hh.setNhaCungCap(nhaCungCapTextField.getText());
        hh.setSoLuong(Integer.parseInt(soLuongSpinner.getValue().toString()));
        return hh;
    }
    public void showToFormNhanVien(NhanVien n) {
        maNVTextField.setText(n.getMaNV());
        tenNVTextField.setText(n.getTenNV());
        if (n.getChucVu().trim().equals("Quan ly")) {
            chucVuComboBox.setSelectedIndex(2);
        } else if (n.getChucVu().trim().equals("Nhan vien kho")) {
            chucVuComboBox.setSelectedIndex(1);
        } 
        
        else {
            chucVuComboBox.setSelectedIndex(0);
        }

        soDienThoaiTextField.setText(n.getSoDienThoai());
        String[] text=n.getNgaySinh().split("-");
        String DoB=text[2].concat("-").concat(text[1]).concat("-").concat(text[0]);
        ngaySinhTextField.setText(DoB);
        
    }
    public void showTOFormHangHoa(HangHoa h){
        maHHTextField.setText(h.getMaHH());
        tenHHTextField.setText(h.getTenHangHoa());
        nhaCungCapTextField.setText(h.getNhaCungCap());
        giaNhapTextField.setText(h.getGiaNhap()+"");
        giaBanTextField.setText(h.getGiaBan()+"");
        soLuongSpinner.setValue(h.getSoLuong());
    }
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        try {
            // TODO add your handling code here:
            ManagerUI managerUI = new ManagerUI(maNV);
            managerUI.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(AdminUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void resetHangHoaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetHangHoaButtonActionPerformed
        // TODO add your handling code here:
        maHHTextField.setText("");
        tenHHTextField.setText("");
        nhaCungCapTextField.setText("");
        soLuongSpinner.setValue(0);
        giaNhapTextField.setText("");
        giaBanTextField.setText("");
        bangHangHoa.setRowCount(0);
        displayDanhSachHangHoa();
    }//GEN-LAST:event_resetHangHoaButtonActionPerformed

    private void timKiemHangHoaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timKiemHangHoaButtonActionPerformed
        // TODO add your handling code here:
        if(listHangHoa.size()!=0){
            if(timKiemHangHoaTextField.getText().toString().trim().equals("")){
                JOptionPane.showMessageDialog(hangHoaPanel, "Nhap ma");
            }else{
                HangHoa h=danhSachHangHoa.getHangHoaWithID(timKiemHangHoaTextField.getText().toString().trim());
                if(h==null){
                    JOptionPane.showMessageDialog(hangHoaPanel, "not found");
                }else{
                    showTOFormHangHoa(h);
                    bangHangHoa.setRowCount(0);
                    showTableHangHoa(1, h);
                }
            }
        }else{
            JOptionPane.showMessageDialog(hangHoaPanel, "No data");
        }
    }//GEN-LAST:event_timKiemHangHoaButtonActionPerformed

    private void suaHangHoaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaHangHoaButtonActionPerformed
        // TODO add your handling code here:
        if(listHangHoa.size()!=0){
            if(clickHH!=-1){
                try {
                    HangHoa oldHH = danhSachHangHoa.getHangHoaAtIndex(clickHH);
                    HangHoa newHH=getHangHoaFromForm();
                    hangHoaJDBC.edit(oldHH, newHH);
                    listHangHoa=hangHoaJDBC.getDataHangHoa();
                    danhSachHangHoa.setList(listHangHoa);
                    bangHangHoa.setRowCount(0);
                    displayDanhSachHangHoa();
                } catch (Exception ex) {
                    Logger.getLogger(AdminUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else{
            JOptionPane.showMessageDialog(hangHoaPanel, "No data");
        }
    }//GEN-LAST:event_suaHangHoaButtonActionPerformed

    private void hangHoaTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hangHoaTableMouseClicked
        // TODO add your handling code here:
        if (listHangHoa.size() != 0) {
            int point = hangHoaTable.getSelectedRow();
            clickHH = point;
            if (clickHH != -1) {
                HangHoa hh = danhSachHangHoa.getHangHoaAtIndex(clickHH);
                showTOFormHangHoa(hh);
            }
        }
    }//GEN-LAST:event_hangHoaTableMouseClicked

    private void timKiemNhanVienButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timKiemNhanVienButtonActionPerformed
        // TODO add your handling code here:
        if(listNhanVien.size() != 0){
            if(timKiemNhanVienTextField.getText().toString().equals("")){
                JOptionPane.showMessageDialog(this, "Nhap ma");
            }else{
                String x=timKiemNhanVienTextField.getText().toString().trim();
                NhanVien nv=danhSachNhanVien.getNhanVienVoiID(x);
                if(nv==null){
                    JOptionPane.showMessageDialog(this, "Not found");
                }else{
                    showToFormNhanVien(nv);
                    bangNhanVien.setRowCount(0);
                    showTableNhanVien(1, nv);
                }
            }
        } else {
            JOptionPane.showMessageDialog(hangHoaPanel, "No data");
        }
    }//GEN-LAST:event_timKiemNhanVienButtonActionPerformed

    private void resetNhanVienButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetNhanVienButtonActionPerformed
        // TODO add your handling code here:
        maNVTextField.setText("");
        tenNVTextField.setText("");
        soDienThoaiTextField.setText("");
        ngaySinhTextField.setText("");
        chucVuComboBox.setSelectedIndex(0);
        bangNhanVien.setRowCount(0);
        displayDanhSachNhanVien();
    }//GEN-LAST:event_resetNhanVienButtonActionPerformed

    private void xoaTatCaNhanVienButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaTatCaNhanVienButtonActionPerformed
        // TODO add your handling code here:
        if (listNhanVien.size() != 0) {
            if (clickNV != 0) {
                try {
                    for (int i = 0; i < listNhanVien.size(); i++) {
                        nhanVienJDBC.delete(listNhanVien.get(i));
                    }
                    listNhanVien = nhanVienJDBC.getDataNhanVien();
                    danhSachNhanVien.setList(listNhanVien);
                    bangNhanVien.setRowCount(0);
                    displayDanhSachNhanVien();
                } catch (Exception ex) {
                    Logger.getLogger(AdminUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(hangHoaPanel, "No data");
        }
    }//GEN-LAST:event_xoaTatCaNhanVienButtonActionPerformed

    private void xoaNhanVienButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaNhanVienButtonActionPerformed
        // TODO add your handling code here:
        if (listNhanVien.size() != 0) {
            if (clickNV != 0) {
                try {
                    NhanVien nv = danhSachNhanVien.getNhanVienAtIndex(clickNV);
                    System.out.println(nv.toString());
                    nhanVienJDBC.delete(nv);
                    listNhanVien = nhanVienJDBC.getDataNhanVien();
                    danhSachNhanVien.setList(listNhanVien);
                    bangNhanVien.setRowCount(0);
                    displayDanhSachNhanVien();
                } catch (Exception ex) {
                    Logger.getLogger(AdminUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(hangHoaPanel, "No data");
        }
    }//GEN-LAST:event_xoaNhanVienButtonActionPerformed

    private void suaNhanVienButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaNhanVienButtonActionPerformed
        // TODO add your handling code here:
        if (emptyCheckNhanVien() == false) {
            try {
                NhanVien oldNV = danhSachNhanVien.getNhanVienAtIndex(clickNV);
                NhanVien newNV = getNhanVienFromForm();
                nhanVienJDBC.edit(oldNV, newNV);
                listNhanVien = nhanVienJDBC.getDataNhanVien();
                danhSachNhanVien.setList(listNhanVien);
                bangNhanVien.setRowCount(0);
                displayDanhSachNhanVien();
            } catch (Exception ex) {
                Logger.getLogger(AdminUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(hangHoaPanel, "No data");
        }
    }//GEN-LAST:event_suaNhanVienButtonActionPerformed

    private void themNhanVienButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themNhanVienButtonActionPerformed
        // TODO add your handling code here:
        if (emptyCheckNhanVien() == false) {
            try {
                String maNV = String.valueOf(maNVTextField.getText());
                String tenNV = String.valueOf(tenNVTextField.getText());
                String chucVu = String.valueOf(chucVuComboBox.getSelectedItem());
                String matKhau = "123456";
                String soDienThoai = String.valueOf(soDienThoaiTextField.getText());
                String DoB = String.valueOf(ngaySinhTextField.getText());
                String[] text = DoB.split("-");
                //                String ngaySinh = text[2] + text[1] + text[0];
                //    System.out.println(ngaySinh);
                // String DoB2=text[2]+text[1]+text[0];
                NhanVien nv = new NhanVien(maNV, tenNV, chucVu, matKhau, soDienThoai, DoB);
                nhanVienJDBC.insertIntoDatabase(nv);
                listNhanVien = nhanVienJDBC.getDataNhanVien();
                danhSachNhanVien.setList(listNhanVien);
                bangNhanVien.setRowCount(0);
                displayDanhSachNhanVien();
            } catch (Exception ex) {
                Logger.getLogger(AdminUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_themNhanVienButtonActionPerformed

    private void ngaySinhTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngaySinhTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ngaySinhTextFieldActionPerformed

    private void nhanVienTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhanVienTableMouseClicked
        // TODO add your handling code here:
        if (listNhanVien.size() != 0) {
            int point = nhanVienTable.getSelectedRow();
            clickNV = point;
            if (clickNV != -1) {
                NhanVien nv = danhSachNhanVien.getNhanVienAtIndex(clickNV);
                System.out.println("NV: "+nv.toString());
                showToFormNhanVien(nv);
            }
        }
    }//GEN-LAST:event_nhanVienTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AdminUI().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(AdminUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> chucVuComboBox;
    private javax.swing.JPanel doanhThuPanel;
    private javax.swing.JTextField giaBanTextField;
    private javax.swing.JTextField giaNhapTextField;
    private javax.swing.JPanel hangHoaPanel;
    private javax.swing.JTable hangHoaTable;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField maHHTextField;
    private javax.swing.JTextField maNVTextField;
    private javax.swing.JTextField ngaySinhTextField;
    private javax.swing.JTextField nhaCungCapTextField;
    private javax.swing.JPanel nhanVienPanel;
    private javax.swing.JTable nhanVienTable;
    private javax.swing.JButton resetHangHoaButton;
    private javax.swing.JButton resetNhanVienButton;
    private javax.swing.JTextField soDienThoaiTextField;
    private javax.swing.JSpinner soLuongSpinner;
    private javax.swing.JButton suaHangHoaButton;
    private javax.swing.JButton suaNhanVienButton;
    private javax.swing.JTabbedPane taoThongBaoPanel;
    private javax.swing.JTextField tenHHTextField;
    private javax.swing.JTextField tenNVTextField;
    private javax.swing.JButton themNhanVienButton;
    private javax.swing.JButton timKiemHangHoaButton;
    private javax.swing.JTextField timKiemHangHoaTextField;
    private javax.swing.JButton timKiemNhanVienButton;
    private javax.swing.JTextField timKiemNhanVienTextField;
    private javax.swing.JButton xoaNhanVienButton;
    private javax.swing.JButton xoaTatCaNhanVienButton;
    // End of variables declaration//GEN-END:variables

    private void showComboBox() {
        ArrayList<String> dSachChucVu = new ArrayList<>();
        dSachChucVu = nhanVien.getdSachChucVu();
        for (String string : dSachChucVu) {
            chucVuComboBox.addItem(string);
        }
    }
}
