/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Lists.*;
import dinhnghia.*;
import java.awt.Graphics;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdbc.*;

/**
 *
 * @author Admin
 */
public class NhapHangHoaUI extends javax.swing.JFrame {

    /**
     * Creates new form NhapHangHoaUI
     */
    DanhSachChiTietHoaDon danhSachChiTietHoaDon;
    DanhSachHangHoa danhSachHangHoa;
    DefaultTableModel defaultTableModel;
    ArrayList<ChiTietHoaDon> list;
    ChiTietHoaDonJDBC chiTietHoaDonJDBC;
    HoaDonJDBC hoaDonJDBC;
    String maHD;
    String maNV;

    ArrayList<ChiTietHoaDon> temporaryList=new ArrayList<>();
    private Graphics g;
    public NhapHangHoaUI(String dataMaNV,String dataMaHD)throws Exception {
        chiTietHoaDonJDBC=new ChiTietHoaDonJDBC();
        hoaDonJDBC=new HoaDonJDBC();
        danhSachHangHoa = new DanhSachHangHoa();
        danhSachHangHoa.insertHangHoa();
        
          maHD=dataMaHD;
           maNV=dataMaNV;
           System.out.println("MaNV: "+maNV+"\t MaHD: "+maHD);
        danhSachChiTietHoaDon = new DanhSachChiTietHoaDon();
        danhSachChiTietHoaDon.insert();
        list=chiTietHoaDonJDBC.getDataChiTietHoaDon();
       // list = danhSachChiTietHoaDon.getList();
        initComponents();
        defaultTableModel = (DefaultTableModel) hangHoaTable.getModel();
        showComboBox();
        display();
    }

    private NhapHangHoaUI() {
    }
    private void display() {
        for (int i = 0; i < temporaryList.size(); i++) {
            showTable(i + 1, temporaryList.get(i));
        }
        displayTK();
    }
    
    
    
    
//
     public int getTotalQuantityOfEachBill(){
        int num=0;
        for (int i = 0; i < temporaryList.size(); i++) {
          //  if(list.get(i).getMaHD().equals(maHD)){
                num=num+temporaryList.get(i).getSoLuong();
          //  }
        }
        return num;
    }
    public int getTotalCostsOfEachBill(){
        int num=0;
        for (int i = 0; i < temporaryList.size(); i++) {
       //     if(list.get(i).getMaHD().equals(maHD)){
                num=num+temporaryList.get(i).getTongTien();
           // }
        }
        return num;
    }
    public String returnDate() {
      //  DateTimeFormatter format1 = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate currentDate = LocalDate.now();
        return currentDate.toString();

    }
    
    
    
    
    
    
    
    
    
    
    public void displayTK() {
        int sumQuantity = 0;
        int sumCosts = 0;
        for (int i = 0; i < temporaryList.size(); i++) {
            sumCosts = sumCosts + temporaryList.get(i).getTongTien();
            sumQuantity = sumQuantity + temporaryList.get(i).getSoLuong();
        }
        defaultTableModel.addRow(new Object[]{
            "", "", "", "", sumQuantity, sumCosts
        });
    }

    public void showTable(int index, ChiTietHoaDon chiTietHoaDon) {
        defaultTableModel.addRow(new Object[]{
            index, chiTietHoaDon.getMaHH(), chiTietHoaDon.getTenHangHoa(), chiTietHoaDon.getGiaBan(), chiTietHoaDon.getSoLuong(), chiTietHoaDon.getTongTien()
        });
    }

    public boolean emptyCheck() {
//        if (donGiaTextField.getText().toString().equals("")) {
//            JOptionPane.showMessageDialog(this, "Input again");
//            donGiaTextField.requestFocus();
//            return true;
//        }
        if (Integer.parseInt(soLuongSpinner.getValue().toString()) == 0) {
            JOptionPane.showMessageDialog(this, "Input again");
            soLuongSpinner.requestFocus();
            return true;
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        maHHLabel = new javax.swing.JLabel();
        tenHHLabel = new javax.swing.JLabel();
        tenHangHoaTextField = new javax.swing.JTextField();
        maHangHoaComboBox = new javax.swing.JComboBox<>();
        donGiaLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tongTienLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        hangHoaTable = new javax.swing.JTable();
        confirmButton = new javax.swing.JButton();
        showCostLabel = new javax.swing.JLabel();
        showTotalCostsLabel = new javax.swing.JLabel();
        soLuongSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nhap Hang Hoa");

        maHHLabel.setText("Ma Hang Hoa");

        tenHHLabel.setText("Ten Hang Hoa");

        maHangHoaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maHangHoaComboBoxActionPerformed(evt);
            }
        });

        donGiaLabel.setText("Don Gia");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("So Luong");

        tongTienLabel.setText("Tong Tien");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit");

        deleteButton.setText("Delete");

        hangHoaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Ma HH", "Ten HH", "Don Gia", "So Luong", "Tong Tien"
            }
        ));
        jScrollPane1.setViewportView(hangHoaTable);

        confirmButton.setText("Comfirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        soLuongSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                soLuongSpinnerStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addComponent(tongTienLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(showTotalCostsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 79, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(255, 255, 255)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(addButton)
                .addGap(93, 93, 93)
                .addComponent(editButton)
                .addGap(136, 136, 136)
                .addComponent(deleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confirmButton)
                .addGap(93, 93, 93))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(maHHLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tenHHLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tenHangHoaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(donGiaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(maHangHoaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(showCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(soLuongSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(donGiaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showCostLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(soLuongSpinner)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                                .addComponent(maHHLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(maHangHoaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showTotalCostsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(tenHHLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tenHangHoaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(tongTienLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(editButton)
                    .addComponent(deleteButton)
                    .addComponent(confirmButton))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        if (emptyCheck() != true) {
            try {
                String id = String.valueOf(maHangHoaComboBox.getSelectedItem());
                String name = String.valueOf(tenHangHoaTextField.getText());
                int donGia = Integer.parseInt(String.valueOf(showCostLabel.getText()));
                int soLuong = Integer.parseInt(soLuongSpinner.getValue().toString());
                int tongTien = soLuong * donGia;
                showTotalCostsLabel.setText(tongTien + "");
                ChiTietHoaDon c = new ChiTietHoaDon(maHD, id, name, soLuong, donGia, tongTien);
                System.out.println(c.toString());
                //  danhSachChiTietHoaDon.add(c);
               // chiTietHoaDonJDBC.insertIntoDatabase(c);
                temporaryList.add(c);
                System.out.println("Quantities: "+getTotalQuantityOfEachBill());
                System.out.println("Costs: "+getTotalCostsOfEachBill());
                defaultTableModel.setRowCount(0);
                display();
            } catch (Exception ex) {
                Logger.getLogger(NhapHangHoaUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            System.out.println("Oke ko");
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void maHangHoaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maHangHoaComboBoxActionPerformed
        // TODO add your handling code here:
        String id = maHangHoaComboBox.getSelectedItem().toString();
        System.out.println("ID: " + id);
        String tenHH = danhSachChiTietHoaDon.getTenHHFromMaHH(id);
        tenHangHoaTextField.setText(tenHH);
        int giaBan = danhSachChiTietHoaDon.getDonGiaFromID(id);
        showCostLabel.setText(giaBan + "");

    }//GEN-LAST:event_maHangHoaComboBoxActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // NhanVienBanHangUI nhanVienBanHangUI=new NhanVienBanHangUI(maNV);

        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to confirm this bill? ");
        if (response == JOptionPane.YES_OPTION) {
            try {
                
                NhanVienBanHangUI nhanVienBanHangUI=new NhanVienBanHangUI(maNV);
             //   NhanVienBanHangUI nhanVienBanHangUI = new NhanVienBanHangUI();
                
                /*
                the job are:
                - push datas up to database
                after go back NhanVienBanHangUI
                - query the total costs and quatity of this bill
                */
                int totalQuantity=getTotalQuantityOfEachBill();
                int totalCosts=getTotalCostsOfEachBill();
                System.out.println("TotalQuantity: "+totalQuantity);
                System.out.println("TotalCosts: "+totalCosts);
                if(totalQuantity!=0){
                    HoaDon hd=new HoaDon(maHD, maNV, returnDate(), totalQuantity, totalCosts);
                    hoaDonJDBC.edit(maHD, hd);
                }else{
                   hoaDonJDBC.delete(maHD); 
                }
                nhanVienBanHangUI.setVisible(true);
                nhanVienBanHangUI.update(g);
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(NhapHangHoaUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void soLuongSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_soLuongSpinnerStateChanged
        // TODO add your handling code here:
        String id = maHangHoaComboBox.getSelectedItem().toString();
        int giaBan = danhSachChiTietHoaDon.getDonGiaFromID(id);
        int soLuong = Integer.parseInt(soLuongSpinner.getValue().toString());
        int tongTien = giaBan * soLuong;
        showTotalCostsLabel.setText(tongTien + "");
    }//GEN-LAST:event_soLuongSpinnerStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhapHangHoaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhapHangHoaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhapHangHoaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhapHangHoaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NhapHangHoaUI().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(NhapHangHoaUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel donGiaLabel;
    private javax.swing.JButton editButton;
    private javax.swing.JTable hangHoaTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel maHHLabel;
    private javax.swing.JComboBox<String> maHangHoaComboBox;
    private javax.swing.JLabel showCostLabel;
    private javax.swing.JLabel showTotalCostsLabel;
    private javax.swing.JSpinner soLuongSpinner;
    private javax.swing.JLabel tenHHLabel;
    private javax.swing.JTextField tenHangHoaTextField;
    private javax.swing.JLabel tongTienLabel;
    // End of variables declaration//GEN-END:variables

    private void showComboBox() {
        ArrayList<String> danhSachMaHH = new ArrayList<>();
        danhSachMaHH = danhSachChiTietHoaDon.getListID();
        for (String string : danhSachMaHH) {
            maHangHoaComboBox.addItem(string);
        }
    }

}
