/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;
import model.Staff;
import java.util.logging.Level;
import java.util.logging.Logger;
import Lists.*;
import java.util.ArrayList;
import jdbc.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class StaffUI extends javax.swing.JFrame {

    /**
     * Creates new form StaffUI
     */
    String staffID;
    StaffJDBC staffJDBC;
    StaffList staffList;
    ArrayList<Staff> listStaff=new ArrayList<>();
    Staff thisStaff=new Staff();
    public StaffUI(String dataController)throws Exception {
        staffJDBC=new StaffJDBC();
        staffList=new StaffList();
        listStaff=staffJDBC.getData();
        staffList.setList(listStaff);
        staffID=dataController;
        thisStaff=staffList.getStaffWithID(staffID);
        initComponents();
        this.setLocationRelativeTo(null);
        showTitle.setText("WELCOME "+staffID+"  " + thisStaff.getStaffName());
        
    }

    private StaffUI() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showTitle = new javax.swing.JLabel();
        showInforLabel = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        changePasswordButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showTitle.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        showTitle.setForeground(new java.awt.Color(255, 0, 0));
        showTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(showTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 53, 645, 52));

        showInforLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(showInforLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 155, 220, 65));

        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 337, 123, 43));

        changePasswordButton.setText("Change Password");
        changePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordButtonActionPerformed(evt);
            }
        });
        getContentPane().add(changePasswordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 337, 140, 43));

        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 337, 123, 43));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        try {
            // TODO add your handling code here:
            LogIn logIn=new LogIn();
            logIn.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(StaffUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        if(thisStaff.getRole().equals("Shop assistant")){
            try {
                ShopAssistantUI banHangUI=new ShopAssistantUI(staffID);
                banHangUI.setVisible(true);
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(StaffUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(thisStaff.getRole().equals("Manager")){
            try {
                AdminUI adminUI=new AdminUI(staffID);
                adminUI.setVisible(true);
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(StaffUI.class.getName()).log(Level.SEVERE, null, ex);
            }
          
        }else{
            try {
                StorageStaffUI nhanVienKhoUI=new StorageStaffUI(staffID);
                nhanVienKhoUI.setVisible(true);
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(StaffUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_homeButtonActionPerformed

    private void changePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordButtonActionPerformed
        // TODO add your handling code here:
        String oldPass, newPass;
        oldPass = JOptionPane.showInputDialog("Input current password");
        if (oldPass != null && oldPass.equals("") == false) {
            Staff nv = staffList.getStaffWithID(staffID);
            if (oldPass.equals(nv.getPassword())) {
                try {
                    newPass = JOptionPane.showInputDialog("Input new password");
                    if (newPass == null) {
                        // JOptionPane.showMessageDialog(rootPane, "Nothing change");
                    } else if (newPass.equals("")) {
                        // JOptionPane.showMessageDialog(rootPane, "Nothing change");
                    } else {
                        staffJDBC.changePassword(staffID, newPass);
                    }
                } catch (Exception ex) {
                    Logger.getLogger(ManagerUI.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "You input wrong password");
            }
        }
    }//GEN-LAST:event_changePasswordButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changePasswordButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton logOutButton;
    private javax.swing.JLabel showInforLabel;
    private javax.swing.JLabel showTitle;
    // End of variables declaration//GEN-END:variables
}
